//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myShop.Entites.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource_en_HTML {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_en_HTML() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("myShop.Entites.Resources.Resource_en_HTML", typeof(Resource_en_HTML).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of operation.
        /// </summary>
        public static string LBActionName {
            get {
                return ResourceManager.GetString("LBActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string LBbtnDelete {
            get {
                return ResourceManager.GetString("LBbtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string LBbtnEdit {
            get {
                return ResourceManager.GetString("LBbtnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new category.
        /// </summary>
        public static string LBbtnSaveNewCategories {
            get {
                return ResourceManager.GetString("LBbtnSaveNewCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string LBButtonClose {
            get {
                return ResourceManager.GetString("LBButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group of categories.
        /// </summary>
        public static string LBCategories {
            get {
                return ResourceManager.GetString("LBCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Description.
        /// </summary>
        public static string LBCategoriesDescription {
            get {
                return ResourceManager.GetString("LBCategoriesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation time.
        /// </summary>
        public static string LBDate {
            get {
                return ResourceManager.GetString("LBDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Description.
        /// </summary>
        public static string LBDescriptionCategoty {
            get {
                return ResourceManager.GetString("LBDescriptionCategoty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string LBEvents {
            get {
                return ResourceManager.GetString("LBEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string LBHomePage {
            get {
                return ResourceManager.GetString("LBHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category operations.
        /// </summary>
        public static string LBLogCategories {
            get {
                return ResourceManager.GetString("LBLogCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name.
        /// </summary>
        public static string LBNameCategoty {
            get {
                return ResourceManager.GetString("LBNameCategoty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop Management.
        /// </summary>
        public static string LBShopManagement {
            get {
                return ResourceManager.GetString("LBShopManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories data table.
        /// </summary>
        public static string LBTableDataCategories {
            get {
                return ResourceManager.GetString("LBTableDataCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string LBUserName {
            get {
                return ResourceManager.GetString("LBUserName", resourceCulture);
            }
        }
    }
}
