//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myShop.Entites.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource_en_Models {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_en_Models() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("myShop.Entites.Resources.Resource_en_Models", typeof(Resource_en_Models).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name is required.
        /// </summary>
        public static string CategoryNameReq {
            get {
                return ResourceManager.GetString("CategoryNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum character is 20 .
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum charcater is 3.
        /// </summary>
        public static string MinLength {
            get {
                return ResourceManager.GetString("MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price must be greater than 0.
        /// </summary>
        public static string MinPrice {
            get {
                return ResourceManager.GetString("MinPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price of product is required.
        /// </summary>
        public static string PriceReq {
            get {
                return ResourceManager.GetString("PriceReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name is required.
        /// </summary>
        public static string ProductNameReq {
            get {
                return ResourceManager.GetString("ProductNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role is Required!.
        /// </summary>
        public static string ReqOfRoleName {
            get {
                return ResourceManager.GetString("ReqOfRoleName", resourceCulture);
            }
        }
    }
}
